/**
 * Pattern 1 — shared character image generation for multi-scene video ads.
 *
 * Generates ONE consistent UGC character image up-front (via Nano Banana 2),
 * persists it to /public/uploads/scene-refs/<uuid>.jpg with a publicly-fetchable
 * URL, and returns the URL for downstream Seedance R2V / I2V calls across all
 * scenes. This is the character-lock primitive that fixes the disconnected-
 * characters bug in seedance-scenes + animated pipelines.
 *
 * Source technique: Alex Robinson's "Claude + Seedance 2.0 = the BEST AI UGC ads"
 * tutorial (Py47FzLdF9E) — generate ONE UGC character image via GPT Image 2,
 * reuse across all scenes as the visual-identity anchor. We swap GPT Image 2
 * for Nano Banana since Nano Banana is already wired and produces comparable
 * quality at 2K resolution.
 */

import { generateImage } from './nano-banana-image';
import { writeFile, mkdir } from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

export interface GenerateUgcCharacterOptions {
  aspectRatio?: '9:16' | '1:1' | '16:9' | '4:5';
  size?: '1K' | '2K' | '4K';
}

export interface GenerateUgcCharacterResult {
  imageUrl: string;          // publicly-fetchable URL (your-domain/uploads/scene-refs/<uuid>.jpg)
  source: 'auto-generated';  // mirrors clone-ad-refs persistence pattern
  description: string;       // the description used (for downstream observability)
  nanoBananaUrl: string;     // raw fal.media URL (kept for debugging; expires after some hours)
}

/**
 * Builds the UGC-character generation prompt template.
 *
 * Mirrors Alex Robinson's recipe from the tutorial: candid, natural, modern
 * apartment setting, eye-level angle. The {description} placeholder is filled
 * with whatever character details the caller has (age, gender, appearance) —
 * if no description is available, the caller should pass a sensible default
 * derived from the brief or product context.
 */
function buildCharacterPrompt(description: string): string {
  const trimmed = description.trim();
  // Compose: style framing first, then the specific character description.
  // Style framing is verbatim from the recipe; only the noun-phrase varies.
  return [
    'Ultra-realistic candid UGC-style photograph.',
    'Natural soft daylight, modern apartment background with neutral decor.',
    'Eye-level angle, upper body composition, expression neutral or slightly engaged.',
    'Single subject only. Crisp focus. No text or captions in image.',
    '',
    `Subject: ${trimmed}`,
  ].join(' ');
}

/**
 * Generate a shared UGC character image and persist it to /public/uploads/scene-refs/.
 *
 * Errors surfaced via err.code:
 *   NANO_BANANA_FAILED — generateImage call threw (key missing, rate limit, etc.)
 *   FILE_WRITE_FAILED  — disk write failed (perms, disk full)
 *   NETWORK_ERROR      — couldn't download the generated image from fal.media
 */
export async function generateUgcCharacter(
  description: string,
  options: GenerateUgcCharacterOptions = {},
): Promise<GenerateUgcCharacterResult> {
  const aspectRatio = options.aspectRatio || '9:16';
  const size = options.size || '2K'; // Alex's recipe uses 2K; matches Nano Banana's tier
  const prompt = buildCharacterPrompt(description);

  console.log(`[CHARACTER-IMAGE] Generating: aspect=${aspectRatio}, size=${size}, desc=${description.substring(0, 100)}…`);

  // Step 1: Generate via Nano Banana
  let nanoResult;
  try {
    nanoResult = await generateImage(prompt, { aspectRatio, resolution: size });
  } catch (e: any) {
    console.error(`[CHARACTER-IMAGE] Nano Banana failed: ${e?.message}`);
    const err = new Error(`Character image generation failed: ${e?.message || 'unknown'}`) as any;
    err.code = 'NANO_BANANA_FAILED';
    err.cause = e;
    throw err;
  }

  console.log(`[CHARACTER-IMAGE] Generated by Nano Banana: ${nanoResult.imageUrl.substring(0, 100)}…`);

  // Step 2: Download from fal.media so we have a permanent local copy. fal.media
  // URLs are publicly fetchable but expire after some hours; we want a stable
  // reference for Seedance R2V/I2V across scene rendering windows.
  let imageBuf: Buffer;
  try {
    const res = await fetch(nanoResult.imageUrl, { signal: AbortSignal.timeout(20000) });
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} fetching ${nanoResult.imageUrl}`);
    }
    imageBuf = Buffer.from(await res.arrayBuffer());
  } catch (e: any) {
    console.error(`[CHARACTER-IMAGE] Download from fal.media failed: ${e?.message}`);
    const err = new Error(`Could not download generated character image: ${e?.message}`) as any;
    err.code = 'NETWORK_ERROR';
    err.cause = e;
    throw err;
  }

  // Step 3: Persist to /public/uploads/scene-refs/<uuid>.png
  // Same pattern as clone-ad-refs (commit 53c6544's middleware exemption).
  // Extension is .png (not .jpg) because Nano Banana 2 returns PNG bytes by
  // default (output_format: 'png' in nano-banana-image.ts:70). Mismatched
  // extension was caught in Pattern 1's first smoke test — Fal.ai's Seedance
  // R2V doesn't care, but Next.js sets Content-Type from extension, so a
  // .jpg-named PNG would serve as image/jpeg and confuse downstream consumers.
  const refUuid = crypto.randomUUID();
  const refDir = path.join(process.cwd(), 'public', 'uploads', 'scene-refs');
  const refFilename = `${refUuid}.png`;
  const refPath = path.join(refDir, refFilename);

  try {
    await mkdir(refDir, { recursive: true });
    await writeFile(refPath, imageBuf);
  } catch (e: any) {
    console.error(`[CHARACTER-IMAGE] File write failed: ${e?.message}`);
    const err = new Error(`Could not save character image: ${e?.message}`) as any;
    err.code = 'FILE_WRITE_FAILED';
    err.cause = e;
    throw err;
  }

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://ymglobalventures.com';
  // URL points to the API route that reads from disk at request time, NOT to
  // /uploads/scene-refs/ directly. Next.js 14 production's static handler
  // doesn't serve runtime-written files (commit 9ff3049's .gitkeep + rsync
  // approach only fixed files that exist at build time). The
  // /api/character-image/[file] route bypasses Next's static manifest and
  // reads from disk on every request. File still persists to scene-refs/
  // on disk (above) — only the URL pattern changes.
  const publicUrl = `${baseUrl}/api/character-image/${refFilename}`;

  console.log(`[CHARACTER-IMAGE] Persisted ${imageBuf.length} bytes → ${publicUrl}`);

  return {
    imageUrl: publicUrl,
    source: 'auto-generated',
    description,
    nanoBananaUrl: nanoResult.imageUrl,
  };
}

/**
 * Derive a sensible default character description from product context when
 * the caller hasn't supplied one. v1 fallback — uses product category cues
 * and the existing avatarStyle config field.
 *
 * Skill: low. We are not training a description LLM; we want a string that
 * Nano Banana will turn into a plausible UGC creator image for that product.
 */
export function deriveCharacterDescriptionFromContext(opts: {
  productName?: string;
  productDescription?: string;
  avatarStyle?: string;  // GeneratorConfig.avatarStyle: 'female_ugc' | 'male_ugc' | etc.
}): string {
  const { productName, avatarStyle } = opts;

  // Avatar-style heuristic — maps existing config field to gender/age archetype.
  // Most ads use female_ugc; fall through to a reasonable default.
  const isMale = (avatarStyle || '').toLowerCase().includes('male') && !avatarStyle?.toLowerCase().includes('female');

  const archetype = isMale
    ? 'man in his early thirties, casual modern style, friendly approachable expression'
    : 'woman in her early thirties, natural makeup, casual modern style, friendly approachable expression';

  // Product-aware tweaks — keep light to avoid overfitting to keywords.
  const productHint = productName ? ` (creator featuring ${productName})` : '';

  return `${archetype}${productHint}`;
}
